
pub fn parse(input: &[u8]) -> Vec<Vec<u8>>{
    input
        .split(|c| *c == b'\n')
        .filter(|line| line.len() > 0)
        .map(|line| line.to_vec())
        .collect()
}


pub const TEST_DATA: &[u8] = b".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
";


#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_parse() {
        let result = parse(TEST_DATA);

        assert_eq!(result.len(), 16);
        assert!(result.iter().all(|line| line.len() == 15));
    }


}